version: '3'

services:

  postgres:
    image: postgres:12-alpine
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aio_stocks
      - POSTGRES_USER=aio_stocks
      - POSTGRES_PASSWORD=aio_stocks

  api:
    build:
      context: ./python
      dockerfile: ./docker/Dockerfile
    command: start_api.sh
    ports:
      - "8080:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aio_stocks
      - DB_PASSWORD=aio_stocks
      - DB_NAME=aio_stocks
      - SETTINGS_MODULE=settings.dev

  parsers:
    build:
      context: ./python
      dockerfile: ./docker/Dockerfile
    command: python parsers/run.py
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aio_stocks
      - DB_PASSWORD=aio_stocks
      - DB_NAME=aio_stocks
      - SETTINGS_MODULE=settings.dev

  api-go:
    build:
      context: ./golang
      dockerfile: ./docker/Dockerfile
    ports:
      - "8081:8001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aio_stocks
      - DB_PASSWORD=aio_stocks
      - DB_NAME=aio_stocks

  api-rust:
    build:
      context: ./rustlang
      dockerfile: ./docker/Dockerfile
    ports:
      - "8082:8002"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=aio_stocks
      - DB_PASSWORD=aio_stocks
      - DB_NAME=aio_stocks

volumes:
  postgres_data:
